# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaiperTravel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'lottie-ios', '~> 3.2.3'
  pod 'Alamofire', '~> 5.4.4'
  pod 'IQKeyboardManagerSwift', '~> 6.5.16'
  pod 'CryptoSwift', '~> 1.8.2'

  # Pods for TaiperTravel

  target 'TaiperTravelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaiperTravelUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end